/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ticketsystem;

import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author umars
 */
public class BookingAppView extends javax.swing.JFrame implements Observer {
    /**
     * Creates new form BookingAppView
     */
    public BookingAppView() {
        initComponents();
        this.setSize(loginPanel.getSize());
        addDates();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createAccountPanel = new javax.swing.JPanel();
        jtfUName = new javax.swing.JTextField();
        jlUName = new javax.swing.JLabel();
        jtfNewPass = new javax.swing.JPasswordField();
        jtfConfirmPass = new javax.swing.JPasswordField();
        jlNewPass = new javax.swing.JLabel();
        jlConfirmPass = new javax.swing.JLabel();
        jbConfirm = new javax.swing.JButton();
        jlFName = new javax.swing.JLabel();
        jtfFName = new javax.swing.JTextField();
        jlHeader = new javax.swing.JLabel();
        homePanel = new javax.swing.JPanel();
        jlCurrentUser = new javax.swing.JLabel();
        jbCreateBooking = new javax.swing.JButton();
        jbViewBookings = new javax.swing.JButton();
        jbMembership = new javax.swing.JButton();
        jbAccSettings = new javax.swing.JButton();
        jbLogOut = new javax.swing.JButton();
        accSettingsPanel = new javax.swing.JPanel();
        jlSettingsUName = new javax.swing.JLabel();
        jlSettingsFName = new javax.swing.JLabel();
        jlChangePass = new javax.swing.JLabel();
        jlSettingsNPass = new javax.swing.JLabel();
        jlSettingsCNPass = new javax.swing.JLabel();
        jlSettingsCPass = new javax.swing.JLabel();
        jtfSettingsUName = new javax.swing.JTextField();
        jtfSettingsFName = new javax.swing.JTextField();
        jbChangePass = new javax.swing.JButton();
        jpfSettingsCPass = new javax.swing.JPasswordField();
        jpfSettingsNPass = new javax.swing.JPasswordField();
        jpfSettingsCNPass = new javax.swing.JPasswordField();
        jbSettingsBack = new javax.swing.JButton();
        jlSettingsPayMethod = new javax.swing.JLabel();
        jbSettingsPayMethod = new javax.swing.JButton();
        addPayAccountPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jpfPAPassword = new javax.swing.JPasswordField();
        jtfPAEmail = new javax.swing.JTextField();
        jbAddPayAcc = new javax.swing.JButton();
        jbBackToSettings = new javax.swing.JButton();
        removePayAccountPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jbRemovePA = new javax.swing.JButton();
        jbCancelRemovePA = new javax.swing.JButton();
        addMembershipPanel = new javax.swing.JPanel();
        jbMembershipBack = new javax.swing.JButton();
        jbAddMembership = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bookTicketPanel = new javax.swing.JPanel();
        jcbJourney = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jcbTravelDate = new javax.swing.JComboBox<>();
        jcbDepartTime = new javax.swing.JComboBox<>();
        jbBookFerry = new javax.swing.JButton();
        jbCancelBooking = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mealList = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        drinkList = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtpDrinkDesc = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtpMealDesc = new javax.swing.JTextPane();
        confirmBookingPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtaBookingDetails = new javax.swing.JTextArea();
        jbConfirmBooking = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        ticketViewPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ticketList = new javax.swing.JList<>();
        jbViewTicket = new javax.swing.JButton();
        jbViewTicketBack = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        jtfUsername = new javax.swing.JTextField();
        jlUsername = new javax.swing.JLabel();
        jlPassword = new javax.swing.JLabel();
        jbLogin = new javax.swing.JButton();
        jtfPassword = new javax.swing.JPasswordField();
        jbCreateAccount = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jlInvalidPassword = new javax.swing.JLabel();

        jlUName.setText("New Username");

        jlNewPass.setText("New Password");

        jlConfirmPass.setText("Confirm Password");

        jbConfirm.setText("Confirm & Create Account");

        jlFName.setText("Full Name");

        jlHeader.setText("Enter your new account details.");

        javax.swing.GroupLayout createAccountPanelLayout = new javax.swing.GroupLayout(createAccountPanel);
        createAccountPanel.setLayout(createAccountPanelLayout);
        createAccountPanelLayout.setHorizontalGroup(
            createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAccountPanelLayout.createSequentialGroup()
                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createAccountPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlNewPass)
                            .addComponent(jlUName)
                            .addComponent(jlFName))
                        .addGap(18, 18, 18)
                        .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfFName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfNewPass, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                .addComponent(jtfUName))))
                    .addGroup(createAccountPanelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jlHeader))
                    .addGroup(createAccountPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jlConfirmPass)
                        .addGap(18, 18, 18)
                        .addComponent(jtfConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createAccountPanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jbConfirm)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        createAccountPanelLayout.setVerticalGroup(
            createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAccountPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jlHeader)
                .addGap(18, 18, 18)
                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlFName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfUName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlUName))
                .addGap(18, 18, 18)
                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNewPass)
                    .addComponent(jtfNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlConfirmPass)
                    .addComponent(jtfConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jbConfirm)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jlCurrentUser.setText("Signed in as: ");

        jbCreateBooking.setText("Make a Booking");

        jbViewBookings.setText("View Bookings");

        jbMembership.setText("Membership");

        jbAccSettings.setText("Account Settings");

        jbLogOut.setText("Log out");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlCurrentUser))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbLogOut))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbViewBookings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbCreateBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbAccSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbMembership, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jbCreateBooking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbViewBookings)
                .addGap(108, 108, 108)
                .addComponent(jbMembership)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAccSettings)
                .addGap(60, 60, 60)
                .addComponent(jlCurrentUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbLogOut)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jlSettingsUName.setText("Username");

        jlSettingsFName.setText("Full name");

        jlChangePass.setText("Change password");

        jlSettingsNPass.setText("New password");

        jlSettingsCNPass.setText("Confirm new password");

        jlSettingsCPass.setText("Current password");

        jtfSettingsUName.setEditable(false);

        jtfSettingsFName.setEditable(false);

        jbChangePass.setText("Change password");

        jbSettingsBack.setText("Back to main menu");

        jlSettingsPayMethod.setText("Saved payment method: ");

        jbSettingsPayMethod.setText("Add/Remove Payment Method");

        javax.swing.GroupLayout accSettingsPanelLayout = new javax.swing.GroupLayout(accSettingsPanel);
        accSettingsPanel.setLayout(accSettingsPanelLayout);
        accSettingsPanelLayout.setHorizontalGroup(
            accSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlSettingsPayMethod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(accSettingsPanelLayout.createSequentialGroup()
                .addGroup(accSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accSettingsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(accSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbSettingsPayMethod)
                            .addGroup(accSettingsPanelLayout.createSequentialGroup()
                                .addGroup(accSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jlSettingsFName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlSettingsUName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(accSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfSettingsFName, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfSettingsUName, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(accSettingsPanelLayout.createSequentialGroup()
                                .addGroup(accSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlSettingsNPass)
                                    .addComponent(jlSettingsCNPass)
                                    .addComponent(jlSettingsCPass))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(accSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jpfSettingsCPass, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(jpfSettingsNPass)
                                    .addComponent(jpfSettingsCNPass)))))
                    .addGroup(accSettingsPanelLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(accSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbSettingsBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbChangePass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(accSettingsPanelLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jlChangePass)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        accSettingsPanelLayout.setVerticalGroup(
            accSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accSettingsPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(accSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSettingsUName)
                    .addComponent(jtfSettingsUName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(accSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSettingsFName)
                    .addComponent(jtfSettingsFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jlSettingsPayMethod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSettingsPayMethod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jlChangePass)
                .addGap(18, 18, 18)
                .addGroup(accSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSettingsCPass)
                    .addComponent(jpfSettingsCPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(accSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSettingsNPass)
                    .addComponent(jpfSettingsNPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSettingsCNPass)
                    .addComponent(jpfSettingsCNPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbChangePass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSettingsBack)
                .addGap(26, 26, 26))
        );

        jLabel1.setText("Pay account details");

        jLabel2.setText("Email address");

        jLabel3.setText("Password");

        jbAddPayAcc.setText("Add Pay account");

        jbBackToSettings.setText("Back to account settings");

        javax.swing.GroupLayout addPayAccountPanelLayout = new javax.swing.GroupLayout(addPayAccountPanel);
        addPayAccountPanel.setLayout(addPayAccountPanelLayout);
        addPayAccountPanelLayout.setHorizontalGroup(
            addPayAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPayAccountPanelLayout.createSequentialGroup()
                .addGroup(addPayAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPayAccountPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(addPayAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addPayAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpfPAPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfPAEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addPayAccountPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(addPayAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbBackToSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbAddPayAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(addPayAccountPanelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        addPayAccountPanelLayout.setVerticalGroup(
            addPayAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPayAccountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(addPayAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfPAEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPayAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpfPAPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(37, 37, 37)
                .addComponent(jbAddPayAcc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbBackToSettings)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        removePayAccountPanel.setPreferredSize(new java.awt.Dimension(304, 130));

        jLabel5.setText("Remove your saved Pay account?");

        jbRemovePA.setText("Yes");

        jbCancelRemovePA.setText("No");

        javax.swing.GroupLayout removePayAccountPanelLayout = new javax.swing.GroupLayout(removePayAccountPanel);
        removePayAccountPanel.setLayout(removePayAccountPanelLayout);
        removePayAccountPanelLayout.setHorizontalGroup(
            removePayAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removePayAccountPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, removePayAccountPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbRemovePA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCancelRemovePA)
                .addGap(17, 17, 17))
        );
        removePayAccountPanelLayout.setVerticalGroup(
            removePayAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removePayAccountPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(removePayAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbRemovePA)
                    .addComponent(jbCancelRemovePA))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jbMembershipBack.setText("Back to main menu");

        jbAddMembership.setText("Become a member");

        jLabel6.setText("You do not currently have a membership with us. Would you like to join?");

        jLabel7.setText("Members recieve a wide range of benefits, including 20% off fares on all");

        jLabel14.setText("of our ferries, 10% off select accommodation, and free travel magazines.");

        jLabel15.setText("Membership Fee: $54.99/year");

        javax.swing.GroupLayout addMembershipPanelLayout = new javax.swing.GroupLayout(addMembershipPanel);
        addMembershipPanel.setLayout(addMembershipPanelLayout);
        addMembershipPanelLayout.setHorizontalGroup(
            addMembershipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMembershipPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addMembershipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addMembershipPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbMembershipBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbAddMembership))
                    .addGroup(addMembershipPanelLayout.createSequentialGroup()
                        .addGroup(addMembershipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        addMembershipPanelLayout.setVerticalGroup(
            addMembershipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addMembershipPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(addMembershipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbMembershipBack)
                    .addComponent(jbAddMembership))
                .addGap(34, 34, 34))
        );

        jcbJourney.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wellington - Picton", "Picton - Wellington" }));

        jLabel8.setText("Journey");

        jLabel9.setText("Travel Date");

        jLabel10.setText("Departure Time");

        jcbDepartTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8:30 AM", "11:00 AM", "1:30 PM", "4:00 PM" }));

        jbBookFerry.setText("Book Ferry");

        jbCancelBooking.setText("Cancel");

        jScrollPane1.setViewportView(mealList);

        jLabel11.setText("Choose a meal");

        jLabel12.setText("Choose a drink");

        jScrollPane2.setViewportView(drinkList);

        jtpDrinkDesc.setEditable(false);
        jtpDrinkDesc.setOpaque(false);
        jScrollPane5.setViewportView(jtpDrinkDesc);

        jtpMealDesc.setEditable(false);
        jtpMealDesc.setOpaque(false);
        jScrollPane6.setViewportView(jtpMealDesc);

        javax.swing.GroupLayout bookTicketPanelLayout = new javax.swing.GroupLayout(bookTicketPanel);
        bookTicketPanel.setLayout(bookTicketPanelLayout);
        bookTicketPanelLayout.setHorizontalGroup(
            bookTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookTicketPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bookTicketPanelLayout.createSequentialGroup()
                        .addGroup(bookTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jbCancelBooking, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(bookTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bookTicketPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(bookTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbJourney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(bookTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jcbTravelDate, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jcbDepartTime, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(bookTicketPanelLayout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(jbBookFerry))))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(bookTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        bookTicketPanelLayout.setVerticalGroup(
            bookTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookTicketPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(bookTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jcbJourney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bookTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbTravelDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbDepartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(bookTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(jScrollPane6))
                .addGap(28, 28, 28)
                .addGroup(bookTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelBooking)
                    .addComponent(jbBookFerry))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jtaBookingDetails.setEditable(false);
        jtaBookingDetails.setColumns(20);
        jtaBookingDetails.setRows(5);
        jtaBookingDetails.setBorder(null);
        jtaBookingDetails.setOpaque(false);
        jScrollPane4.setViewportView(jtaBookingDetails);

        jbConfirmBooking.setText("Confirm Booking");

        jbCancel.setText("Cancel");

        jLabel13.setText("Confirm current booking?");

        javax.swing.GroupLayout confirmBookingPanelLayout = new javax.swing.GroupLayout(confirmBookingPanel);
        confirmBookingPanel.setLayout(confirmBookingPanelLayout);
        confirmBookingPanelLayout.setHorizontalGroup(
            confirmBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmBookingPanelLayout.createSequentialGroup()
                .addGroup(confirmBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(confirmBookingPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                    .addGroup(confirmBookingPanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(confirmBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbConfirmBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(confirmBookingPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        confirmBookingPanelLayout.setVerticalGroup(
            confirmBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmBookingPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbConfirmBooking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCancel)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(ticketList);

        jbViewTicket.setText("View Ticket");

        jbViewTicketBack.setText("Back to main menu");

        jLabel16.setText("Booking List");

        javax.swing.GroupLayout ticketViewPanelLayout = new javax.swing.GroupLayout(ticketViewPanel);
        ticketViewPanel.setLayout(ticketViewPanelLayout);
        ticketViewPanelLayout.setHorizontalGroup(
            ticketViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketViewPanelLayout.createSequentialGroup()
                .addGroup(ticketViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ticketViewPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
                    .addGroup(ticketViewPanelLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(ticketViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbViewTicketBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbViewTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(ticketViewPanelLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ticketViewPanelLayout.setVerticalGroup(
            ticketViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketViewPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbViewTicket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbViewTicketBack)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jlUsername.setText("Username");

        jlPassword.setText("Password");

        jbLogin.setText("Login");

        jbCreateAccount.setText("Create Account");

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Book A Ferry");

        jlInvalidPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlUsername)
                    .addComponent(jlPassword))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(jtfUsername))
                .addGap(59, 59, 59))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbCreateAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(jbLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlInvalidPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPassword)
                    .addComponent(jtfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlInvalidPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCreateAccount)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 238, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 173, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addActionListener(ActionListener al) {
        // Add action listeners to the JButtons.
        
        // Login/Create Account panel buttons
        jbLogin.addActionListener(al);
        jbCreateAccount.addActionListener(al);
        jbConfirm.addActionListener(al);
        
        // Home panel buttons
        jbCreateBooking.addActionListener(al);
        jbViewBookings.addActionListener(al);
        jbMembership.addActionListener(al);
        jbAccSettings.addActionListener(al);
        jbLogOut.addActionListener(al);
        
        // accSettingsPanel buttons
        jbChangePass.addActionListener(al);
        jbSettingsBack.addActionListener(al);
        jbSettingsPayMethod.addActionListener(al);
        
        // addPayAccountPanel buttons
        jbAddPayAcc.addActionListener(al);
        jbBackToSettings.addActionListener(al);
        
        // removePayAccountPanel buttons
        jbRemovePA.addActionListener(al);
        jbCancelRemovePA.addActionListener(al);
        
        // addMembershipPanel buttons
        jbAddMembership.addActionListener(al);
        jbMembershipBack.addActionListener(al);
        
        // bookTicketPanel buttons
        jbBookFerry.addActionListener(al);
        jbCancelBooking.addActionListener(al);
        
        // confirmBookingPanel buttons
        jbConfirmBooking.addActionListener(al);
        jbCancel.addActionListener(al);
        
        // ticketViewPanel buttons
        jbViewTicket.addActionListener(al);
        jbViewTicketBack.addActionListener(al);
    }
    
    // Add ListSelectionListeners to mealList and drinkList so the program responds to each selection.
    public void addListSelectionListener(ListSelectionListener l) {
        mealList.addListSelectionListener(l);
        drinkList.addListSelectionListener(l);
    }
    
    private void addDates() {
        // Populate Travel Date combo box with travel dates for the next month, in DD/MM/YYYY format.
        LocalDate sysDate = LocalDate.now().plusMonths(1);
                
        jcbTravelDate.addItem("3/"+sysDate.getMonthValue()+"/"+sysDate.getYear());
        jcbTravelDate.addItem("7/"+sysDate.getMonthValue()+"/"+sysDate.getYear());
        jcbTravelDate.addItem("14/"+sysDate.getMonthValue()+"/"+sysDate.getYear());
        jcbTravelDate.addItem("20/"+sysDate.getMonthValue()+"/"+sysDate.getYear());
        jcbTravelDate.addItem("22/"+sysDate.getMonthValue()+"/"+sysDate.getYear());
    }
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BookingAppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(BookingAppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(BookingAppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(BookingAppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new BookingAppView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accSettingsPanel;
    private javax.swing.JPanel addMembershipPanel;
    private javax.swing.JPanel addPayAccountPanel;
    private javax.swing.JPanel bookTicketPanel;
    private javax.swing.JPanel confirmBookingPanel;
    private javax.swing.JPanel createAccountPanel;
    public javax.swing.JList<String> drinkList;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton jbAccSettings;
    private javax.swing.JButton jbAddMembership;
    private javax.swing.JButton jbAddPayAcc;
    private javax.swing.JButton jbBackToSettings;
    private javax.swing.JButton jbBookFerry;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbCancelBooking;
    private javax.swing.JButton jbCancelRemovePA;
    private javax.swing.JButton jbChangePass;
    private javax.swing.JButton jbConfirm;
    private javax.swing.JButton jbConfirmBooking;
    private javax.swing.JButton jbCreateAccount;
    private javax.swing.JButton jbCreateBooking;
    private javax.swing.JButton jbLogOut;
    private javax.swing.JButton jbLogin;
    private javax.swing.JButton jbMembership;
    private javax.swing.JButton jbMembershipBack;
    private javax.swing.JButton jbRemovePA;
    private javax.swing.JButton jbSettingsBack;
    private javax.swing.JButton jbSettingsPayMethod;
    private javax.swing.JButton jbViewBookings;
    private javax.swing.JButton jbViewTicket;
    private javax.swing.JButton jbViewTicketBack;
    public javax.swing.JComboBox<String> jcbDepartTime;
    public javax.swing.JComboBox<String> jcbJourney;
    public javax.swing.JComboBox<String> jcbTravelDate;
    private javax.swing.JLabel jlChangePass;
    private javax.swing.JLabel jlConfirmPass;
    private javax.swing.JLabel jlCurrentUser;
    private javax.swing.JLabel jlFName;
    private javax.swing.JLabel jlHeader;
    private javax.swing.JLabel jlInvalidPassword;
    private javax.swing.JLabel jlNewPass;
    private javax.swing.JLabel jlPassword;
    private javax.swing.JLabel jlSettingsCNPass;
    private javax.swing.JLabel jlSettingsCPass;
    private javax.swing.JLabel jlSettingsFName;
    private javax.swing.JLabel jlSettingsNPass;
    private javax.swing.JLabel jlSettingsPayMethod;
    private javax.swing.JLabel jlSettingsUName;
    private javax.swing.JLabel jlUName;
    private javax.swing.JLabel jlUsername;
    public javax.swing.JPasswordField jpfPAPassword;
    public javax.swing.JPasswordField jpfSettingsCNPass;
    public javax.swing.JPasswordField jpfSettingsCPass;
    public javax.swing.JPasswordField jpfSettingsNPass;
    public javax.swing.JTextArea jtaBookingDetails;
    public javax.swing.JPasswordField jtfConfirmPass;
    public javax.swing.JTextField jtfFName;
    public javax.swing.JPasswordField jtfNewPass;
    public javax.swing.JTextField jtfPAEmail;
    public javax.swing.JPasswordField jtfPassword;
    private javax.swing.JTextField jtfSettingsFName;
    private javax.swing.JTextField jtfSettingsUName;
    public javax.swing.JTextField jtfUName;
    public javax.swing.JTextField jtfUsername;
    private javax.swing.JTextPane jtpDrinkDesc;
    private javax.swing.JTextPane jtpMealDesc;
    private javax.swing.JPanel loginPanel;
    public javax.swing.JList<String> mealList;
    private javax.swing.JPanel removePayAccountPanel;
    public javax.swing.JList<String> ticketList;
    private javax.swing.JPanel ticketViewPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        // Take in an Output object, update the view based on Output.action.
        Output argument = (Output) arg;
        switch (argument.action) {
            case Output.ADD_PAY_ACCOUNT:
                // Prompt the user to add a Pay account, set the text fields to initially be empty.
                jtfPAEmail.setText("");
                jpfPAPassword.setText("");
                setContentPane(addPayAccountPanel);
                setSize(addPayAccountPanel.getPreferredSize());
                break;
            case Output.ADD_PAY_ACCOUNT_SUCCESS:
                JOptionPane.showMessageDialog(null, "Your Pay account has been added.", "Success", JOptionPane.PLAIN_MESSAGE);
                // Show the user's Pay account email on the account settings panel.
                jlSettingsPayMethod.setText("Saved payment method: "+argument.outputString1);
                setContentPane(accSettingsPanel);
                setSize(accSettingsPanel.getPreferredSize());
                break;
            case Output.BACK_TO_HOME:
                // Send the user back to the home panel/
                setContentPane(homePanel);
                setSize(homePanel.getPreferredSize());
                break;
            case Output.BOOKING_ERROR:
                JOptionPane.showMessageDialog(null, argument.outputString1, "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case Output.CHANGE_PASSWORD_SUCCESS:
                JOptionPane.showMessageDialog(null, "Your password has successfuly been changed.", "Success", JOptionPane.PLAIN_MESSAGE);
                // Empty the password fields.
                jpfSettingsCPass.setText("");
                jpfSettingsNPass.setText("");
                jpfSettingsCNPass.setText("");
                break;
            case Output.CONFIRM_BOOKING_PROMPT:
                // Display booking details to the panel, prompt user to confirm.
                jtaBookingDetails.setText(argument.outputString1+"\n\n"+argument.outputString2);
                setContentPane(confirmBookingPanel);
                setSize(confirmBookingPanel.getPreferredSize());
                break;
            case Output.CONFIRM_BOOKING_SUCCESS:
                // Display booking confirmation details on the message box.
                String confirmation = argument.outputString1+"\n"+argument.outputString2+"\n"+argument.outputString3;
                JOptionPane.showMessageDialog(null, confirmation, "Booking Successful", JOptionPane.INFORMATION_MESSAGE);
                setContentPane(homePanel);
                setSize(homePanel.getPreferredSize());
                break;
            case Output.CREATE_ACCOUNT:
                setContentPane(createAccountPanel);
                setSize(createAccountPanel.getPreferredSize());
                break;
            case Output.CREATE_ACCOUNT_SUCCESS:
                JOptionPane.showMessageDialog(null, "Your account has successfully been created.", "Success", JOptionPane.PLAIN_MESSAGE);
                // Display username of the current user.
                jlCurrentUser.setText("Signed in as: "+argument.outputString1);
                setContentPane(homePanel);
                setSize(homePanel.getPreferredSize());
                break;
            case Output.CREATE_BOOKING:
                // Display the booking panel, undo any prior item selections.
                mealList.setSelectedValue(null, false);
                jtpMealDesc.setText("");
                drinkList.setSelectedValue(null, false);
                jtpDrinkDesc.setText("");
                setContentPane(bookTicketPanel);
                setSize(bookTicketPanel.getPreferredSize());
                break;
            case Output.INVALID_LOGIN_CREDENTIALS:
                jlInvalidPassword.setText("Invalid login credentials. Try again.");
                break;
            case Output.INVALID_NAME:
                JOptionPane.showMessageDialog(null, "Full name must only contain letters and spaces.", "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case Output.INVALID_NAME_LENGTH:
                JOptionPane.showMessageDialog(null, "Full name must be between 5 and 40 characters in length.", "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case Output.INVALID_NEW_PASSWORD:
                JOptionPane.showMessageDialog(null, "Passwords must be 8 to 20 characters in length and must not contain spaces.", "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case Output.INVALID_PA_EMAIL:
                JOptionPane.showMessageDialog(null, "Please enter a valid email address.", "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case Output.INVALID_PA_PASSWORD:
                JOptionPane.showMessageDialog(null, "Please enter a valid password. (Min. 8 characters, max. 20 characters)", "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case Output.INVALID_USERNAME:
                JOptionPane.showMessageDialog(null, "Username must be 5 to 15 characters in length and must not contain spaces.", "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case Output.LOG_IN_SUCCESS:
                jlCurrentUser.setText("Signed in as: "+argument.outputString1);
                jtfPassword.setText("");
                jlInvalidPassword.setText("");
                setContentPane(homePanel);
                setSize(homePanel.getPreferredSize());
                break;
            case Output.LOG_OUT:
                setContentPane(loginPanel);
                setSize(loginPanel.getPreferredSize());
                break;
            case Output.NEW_PASSWORD_MISMATCH:
                JOptionPane.showMessageDialog(null, "Passwords do not match.", "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case Output.PA_IN_USE:
                JOptionPane.showMessageDialog(null, "This Pay account is already in use.", "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case Output.POPULATE_MEAL_DRINK_LIST:
                // Add meal and drink items from the array lists to the list models.
                DefaultListModel mealListModel = new DefaultListModel();
                mealListModel.addElement("No meal");
                for (Meal m: argument.mealList) {
                    mealListModel.addElement(m.getName());
                }
                
                DefaultListModel drinkListModel = new DefaultListModel();
                drinkListModel.addElement("No drink");
                for (Drink d: argument.drinkList) {
                    drinkListModel.addElement(d.getName());
                }
                // Add the list model items to the JLists.
                mealList.setModel(mealListModel);
                drinkList.setModel(drinkListModel);
                break;
            case Output.PRINT_MEAL_INFO:
                String mealInfo = argument.outputString1;
                if (!mealInfo.equals("")) {
                    mealInfo += "\n\n"+argument.outputString2;
                }
                jtpMealDesc.setText(mealInfo);
                break;
            case Output.PRINT_DRINK_INFO:
                String drinkInfo = argument.outputString1;
                if (!drinkInfo.equals("")) {
                    drinkInfo += "\n\n"+argument.outputString2;
                }
                jtpDrinkDesc.setText(drinkInfo);
                break;
            case Output.REGISTER_MEMBER_ERROR:
                JOptionPane.showMessageDialog(null, "You do not have a payment method saved.", "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case Output.REGISTER_MEMBER_SUCCESS:
                // Message box displayed upon registering new membership.
                String newMemberMessage = "Thank you for becoming a member!\n"
                        + "Your new membership ID: "+argument.outputString1+"\n"
                        + "Membership expiry date: "+argument.outputString2;
                JOptionPane.showMessageDialog(null, newMemberMessage, "Success", JOptionPane.PLAIN_MESSAGE);
                setContentPane(homePanel);
                setSize(homePanel.getPreferredSize());
                break;
            case Output.REMOVE_PAY_ACCOUNT:
                // Prompt the user to remove their Pay account.
                setContentPane(removePayAccountPanel);
                setSize(removePayAccountPanel.getPreferredSize());
                break;
            case Output.REMOVE_PAY_ACCOUNT_SUCCESS:
                JOptionPane.showMessageDialog(null, "Your Pay account has been removed.", "Success", JOptionPane.PLAIN_MESSAGE);
                jlSettingsPayMethod.setText("No payment method saved.");
                setContentPane(accSettingsPanel);
                setSize(accSettingsPanel.getPreferredSize());
                break;
            case Output.USERNAME_EXISTS:
                JOptionPane.showMessageDialog(null, "The username you entered is already in use.", "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case Output.VIEW_ACCOUNT_SETTINGS:
                // Display the current user's full name, username, and Pay account email on the settings panel.
                jtfSettingsUName.setText(argument.outputString1);
                jtfSettingsFName.setText(argument.outputString2);
                jlSettingsPayMethod.setText(argument.outputString3);
                // Empty password fields.
                jpfSettingsCPass.setText("");
                jpfSettingsNPass.setText("");
                jpfSettingsCNPass.setText("");
                setContentPane(accSettingsPanel);
                setSize(accSettingsPanel.getPreferredSize());
                break;
            case Output.WRONG_CURRENT_PASSWORD:
                JOptionPane.showMessageDialog(null, "The current password you entered does not match your actual current password.", "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case Output.VIEW_MEMBERSHIP:
                String message = "Your membership ID: "+argument.outputString1+"\n"
                        + "Membership expiry date: "+argument.outputString2;
                JOptionPane.showMessageDialog(null, message, "Membership", JOptionPane.INFORMATION_MESSAGE);
                break;
            case Output.VIEW_MEMBERSHIP_OPTION:
                setContentPane(addMembershipPanel);
                setSize(addMembershipPanel.getPreferredSize());
                break;
            case Output.VIEW_TICKET:
                JOptionPane.showMessageDialog(null, argument.outputString1+"\n"+argument.outputString2, "Ticket", JOptionPane.PLAIN_MESSAGE);
                break;
            case Output.VIEW_TICKET_LIST:
                // Add ticket list items to the list model.
                DefaultListModel ticketListModel = new DefaultListModel();
                for (Ticket t: argument.ticketList) {
                    ticketListModel.addElement(t.getTicketNo()+": "+t.getDestination()+" "+t.getTravelDate().format(DateTimeFormatter.ofPattern("dd-LLL-yyyy")));
                }
                // Add items from the model to the JList.
                ticketList.setModel(ticketListModel);
                setContentPane(ticketViewPanel);
                setSize(ticketViewPanel.getPreferredSize());
                break;

        }
    }
}
