package ticketsystem;

public enum Input {
    LOG_IN, 
    CREATE_ACCOUNT, 
    CONFIRM_CREATE_ACCOUNT, 
    INVALID_LOGIN_CREDENTIALS, 
    USERNAME_EXISTS, 
    INVALID_USERNAME,
    INVALID_NAME,
    INVALID_NAME_LENGTH,
    INVALID_NEW_PASSWORD, 
    NEW_PASSWORD_MISMATCH;
}
