package ticketsystem;

public enum Input {
    CREATE_ACCOUNT, 
    CREATE_ACCOUNT_SUCCESS, 
    INVALID_LOGIN_CREDENTIALS, 
    INVALID_NAME,
    INVALID_NAME_LENGTH,
    INVALID_NEW_PASSWORD,
    INVALID_USERNAME,
    LOG_IN, 
    NEW_PASSWORD_MISMATCH,
    USERNAME_EXISTS;
}
